In [1]:
import pandas as pd
import sqlite3

### Reading sql tables to get information about drivers and teams

In [2]:
conn = sqlite3.connect('tour_de_france.db')

In [3]:
riders = pd.read_sql_query("SELECT * FROM riders", conn)
teams = pd.read_sql_query("SELECT * FROM teams", conn)

In [4]:
teams

,name,link
0,JUMBO-VISMA,https://www.letour.fr/en/team/TJV/jumbo-visma
1,UAE TEAM EMIRATES,https://www.letour.fr/en/team/UAD/uae-team-emi...
2,INEOS GRENADIERS,https://www.letour.fr/en/team/IGD/ineos-grenad...
3,GROUPAMA - FDJ,https://www.letour.fr/en/team/GFC/groupama-fdj
4,EF EDUCATION - EASYPOST,https://www.letour.fr/en/team/EFE/ef-education...
5,SOUDAL QUICK-STEP,https://www.letour.fr/en/team/SOQ/soudal-quick...
6,BAHRAIN VICTORIOUS,https://www.letour.fr/en/team/TBV/bahrain-vict...
7,BORA - HANSGROHE,https://www.letour.fr/en/team/BOH/bora-hansgrohe
8,LIDL - TREK,https://www.letour.fr/en/team/LTK/lidl-trek
9,AG2R CITROEN TEAM,https://www.letour.fr/en/team/ACT/ag2r-citroen...
10,ALPECIN-DECEUNINCK,https://www.letour.fr/en/team/ADC/alpecin-dece...
11,INTERMARCHÉ - CIRCUS - WANTY,https://www.letour.fr/en/team/ICW/intermarche-...
12,COFIDIS,https://www.letour.fr/en/team/COF/cofidis
13,MOVISTAR TEAM,https://www.letour.fr/en/team/MOV/movistar-team
14,TEAM DSM - FIRMENICH,https://www.letour.fr/en/team/DSM/team-dsm-fir...
15,ISRAEL - PREMIER TECH,https://www.letour.fr/en/team/IPT/israel-premi...
16,TEAM JAYCO ALULA,https://www.letour.fr/en/team/JAY/team-jayco-a...
17,TEAM ARKEA - SAMSIC,https://www.letour.fr/en/team/ARK/team-arkea-s...
18,LOTTO DSTNY,https://www.letour.fr/en/team/LTD/lotto-dstny
19,ASTANA QAZAQSTAN TEAM,https://www.letour.fr/en/team/AST/astana-qazaq...
20,UNO-X PRO CYCLING TEAM,https://www.letour.fr/en/team/UXT/uno-x-pro-cy...
21,TOTALENERGIES,https://www.letour.fr/en/team/TEN/totalenergies

In [5]:
riders

,bib,name,team,link,image,country,birth,age,rankings,performance
0,1,JONAS VINGEGAARD,JUMBO-VISMA,https://www.letour.fr/en/rider/1/jumbo-visma/j...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,(den),1996-10-12,26,"['9', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '26', '57']"
1,2,TIESJ BENOOT,JUMBO-VISMA,https://www.letour.fr/en/rider/2/jumbo-visma/t...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,(bel),1994-03-11,29,"['-', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '7', '42']"
2,3,WILCO KELDERMAN,JUMBO-VISMA,https://www.letour.fr/en/rider/3/jumbo-visma/w...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,(ned),1991-03-25,32,"['14', '-', '-', '-', '-', '-', '-', '-', '-',...","['0', '0', '17', '62']"
3,4,SEPP KUSS,JUMBO-VISMA,https://www.letour.fr/en/rider/4/jumbo-visma/s...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,(usa),1994-09-13,28,"['31', '-', '-', '-', '-', '-', '-', '-', '-',...","['0', '0', '8', '15']"
4,5,CHRISTOPHE LAPORTE,JUMBO-VISMA,https://www.letour.fr/en/rider/5/jumbo-visma/c...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,(fra),1992-12-11,30,"['-', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '30', '64']"
...,...,...,...,...,...,...,...,...,...,...
171,214,STEFF CRAS,TOTALENERGIES,https://www.letour.fr/en/rider/214/totalenergi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,(bel),1996-02-13,27,"['19', '-', '-', '-', '-', '-', '-', '-', '-',...","['0', '0', '1', '8']"
172,215,VALENTIN FERRON,TOTALENERGIES,https://www.letour.fr/en/rider/215/totalenergi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,(fra),1998-02-08,25,"['-', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '3', '11']"
173,216,PIERRE LATOUR,TOTALENERGIES,https://www.letour.fr/en/rider/216/totalenergi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,(fra),1993-10-12,29,"['-', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '7', '42']"
174,217,DANIEL OSS,TOTALENERGIES,https://www.letour.fr/en/rider/217/totalenergi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,(ita),1987-01-13,36,"['-', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '2', '19']"
175,218,ANTHONY TURGIS,TOTALENERGIES,https://www.letour.fr/en/rider/218/totalenergi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,(fra),1994-05-16,29,"['-', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '7', '25']"

In [6]:
riders['country'] = riders['country'].apply(lambda x: x.strip('()').upper())

In [7]:
# convert data to relevant data types
riders['birth'] = riders['birth'].astype('datetime64[ns]')
riders['age'] = riders['age'].astype(int)

In [8]:
riders.dtypes

bib                     int64
name                   object
team                   object
link                   object
image                  object
country                object
birth          datetime64[ns]
age                     int64
rankings               object
performance            object
dtype: object

In [9]:
riders.sort_values(by='age', ascending=True)

,bib,name,team,link,image,country,birth,age,rankings,performance
70,87,QUINN SIMMONS,LIDL - TREK,https://www.letour.fr/en/rider/87/lidl-trek/qu...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,USA,2001-05-08,22,"['-', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '19', '27']"
22,27,CARLOS RODRIGUEZ CANO,INEOS GRENADIERS,https://www.letour.fr/en/rider/27/ineos-grenad...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,ESP,2001-02-02,22,"['13', '-', '-', '-', '-', '-', '-', '-', '-',...","['0', '0', '10', '22']"
66,83,SKJELMOSE MATTIAS JENSEN,LIDL - TREK,https://www.letour.fr/en/rider/83/lidl-trek/sk...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,DEN,2000-09-26,22,"['8', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '9', '37']"
118,147,KEVIN VERMAERKE,TEAM DSM - FIRMENICH,https://www.letour.fr/en/rider/147/team-dsm-fi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,USA,2000-10-16,22,"['-', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '1', '3']"
21,26,THOMAS PIDCOCK,INEOS GRENADIERS,https://www.letour.fr/en/rider/26/ineos-grenad...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,GBR,1999-07-30,23,"['29', '-', '-', '-', '-', '-', '-', '-', '-',...","['0', '0', '17', '38']"
...,...,...,...,...,...,...,...,...,...,...
98,123,SIMON GESCHKE,COFIDIS,https://www.letour.fr/en/rider/123/cofidis/sim...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,GER,1986-03-13,37,"['62', '-', '-', '-', '-', '-', '-', '-', '-',...","['0', '0', '4', '26']"
47,58,MICHAEL MØRKØV,SOUDAL QUICK-STEP,https://www.letour.fr/en/rider/58/soudal-quick...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,DEN,1985-04-30,38,"['-', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '11', '42']"
152,191,MARK CAVENDISH,ASTANA QAZAQSTAN TEAM,https://www.letour.fr/en/rider/191/astana-qaza...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,GBR,1985-05-21,38,"['-', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '167', '266']"
158,197,LUIS LEON SANCHEZ,ASTANA QAZAQSTAN TEAM,https://www.letour.fr/en/rider/197/astana-qaza...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,ESP,1983-11-24,39,"['38', '-', '-', '-', '-', '-', '-', '-', '-',...","['0', '0', '47', '116']"
44,55,DRIES DEVENYNS,SOUDAL QUICK-STEP,https://www.letour.fr/en/rider/55/soudal-quick...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,BEL,1983-07-22,39,"['-', '-', '-', '-', '-', '-', '-', '-', '-', ...","['0', '0', '13', '23']"

In [10]:
riders.groupby(['country'], sort=True).count()

         bib  name  team  link  image  birth  age  rankings  performance
country
AUS       12    12    12    12     12     12   12        12           12
AUT        6     6     6     6      6      6    6         6            6
BEL       21    21    21    21     21     21   21        21           21
CAN        3     3     3     3      3      3    3         3            3
COL        5     5     5     5      5      5    5         5            5
CRC        1     1     1     1      1      1    1         1            1
DEN       11    11    11    11     11     11   11        11           11
ECU        1     1     1     1      1      1    1         1            1
ERI        1     1     1     1      1      1    1         1            1
ESP       14    14    14    14     14     14   14        14           14
FRA       32    32    32    32     32     32   32        32           32
GBR        7     7     7     7      7      7    7         7            7
GER        7     7     7     7      7      7    7         7            7
ITA        7     7     7     7      7      7    7         7            7
KAZ        2     2     2     2      2      2    2         2            2
LAT        1     1     1     1      1      1    1         1            1
LUX        3     3     3     3      3      3    3         3            3
NED       14    14    14    14     14     14   14        14           14
NOR        8     8     8     8      8      8    8         8            8
NZL        2     2     2     2      2      2    2         2            2
POL        2     2     2     2      2      2    2         2            2
POR        3     3     3     3      3      3    3         3            3
RSA        1     1     1     1      1      1    1         1            1
SLO        3     3     3     3      3      3    3         3            3
SUI        2     2     2     2      2      2    2         2            2
SVK        1     1     1     1      1      1    1         1            1
USA        6     6     6     6      6      6    6         6            6

In [11]:
def split_column(df, column, new_columns):
    '''Split a column into multiple columns'''
    df[new_columns] = df[column].apply(lambda x: pd.Series(str(x).split(",")))
    df[new_columns] = df[new_columns].apply(lambda x: x.str.strip(" [''] "))
    df.drop(columns=[column], inplace=True)

In [12]:
performance_cols = ['intermediate sprint', 'stages victory', 'Victories', 'Podiums']
split_column(riders, 'performance', performance_cols)

split_column(riders, 'rankings', [i for i in range(1, 22)])

In [13]:
riders

,bib,name,team,link,image,country,birth,age,intermediate sprint,stages victory,...,12,13,14,15,16,17,18,19,20,21
0,1,JONAS VINGEGAARD,JUMBO-VISMA,https://www.letour.fr/en/rider/1/jumbo-visma/j...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,DEN,1996-10-12,26,0,0,...,-,-,-,-,-,-,-,-,-,-
1,2,TIESJ BENOOT,JUMBO-VISMA,https://www.letour.fr/en/rider/2/jumbo-visma/t...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,BEL,1994-03-11,29,0,0,...,-,-,-,-,-,-,-,-,-,-
2,3,WILCO KELDERMAN,JUMBO-VISMA,https://www.letour.fr/en/rider/3/jumbo-visma/w...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,NED,1991-03-25,32,0,0,...,-,-,-,-,-,-,-,-,-,-
3,4,SEPP KUSS,JUMBO-VISMA,https://www.letour.fr/en/rider/4/jumbo-visma/s...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,USA,1994-09-13,28,0,0,...,-,-,-,-,-,-,-,-,-,-
4,5,CHRISTOPHE LAPORTE,JUMBO-VISMA,https://www.letour.fr/en/rider/5/jumbo-visma/c...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,FRA,1992-12-11,30,0,0,...,-,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,214,STEFF CRAS,TOTALENERGIES,https://www.letour.fr/en/rider/214/totalenergi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,BEL,1996-02-13,27,0,0,...,-,-,-,-,-,-,-,-,-,-
172,215,VALENTIN FERRON,TOTALENERGIES,https://www.letour.fr/en/rider/215/totalenergi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,FRA,1998-02-08,25,0,0,...,-,-,-,-,-,-,-,-,-,-
173,216,PIERRE LATOUR,TOTALENERGIES,https://www.letour.fr/en/rider/216/totalenergi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,FRA,1993-10-12,29,0,0,...,-,-,-,-,-,-,-,-,-,-
174,217,DANIEL OSS,TOTALENERGIES,https://www.letour.fr/en/rider/217/totalenergi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,ITA,1987-01-13,36,0,0,...,-,-,-,-,-,-,-,-,-,-
175,218,ANTHONY TURGIS,TOTALENERGIES,https://www.letour.fr/en/rider/218/totalenergi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,FRA,1994-05-16,29,0,0,...,-,-,-,-,-,-,-,-,-,-

In [26]:
riders.sort_values(by=['name'], ascending=False)

,bib,name,team,link,image,country,birth,age,intermediate sprint,stages victory,...,12,13,14,15,16,17,18,19,20,21
46,57,YVES LAMPAERT,SOUDAL QUICK-STEP,https://www.letour.fr/en/rider/57/soudal-quick...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,BEL,1991-04-10,32,0,0,...,-,-,-,-,-,-,-,-,-,-
155,194,YEVGENIY FEDOROV,ASTANA QAZAQSTAN TEAM,https://www.letour.fr/en/rider/194/astana-qaza...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,KAZ,2000-02-16,23,0,0,...,-,-,-,-,-,-,-,-,-,-
5,6,WOUT VAN AERT,JUMBO-VISMA,https://www.letour.fr/en/rider/6/jumbo-visma/w...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,BEL,1994-09-15,28,0,0,...,-,-,-,-,-,-,-,-,-,-
54,68,WOUT POELS,BAHRAIN VICTORIOUS,https://www.letour.fr/en/rider/68/bahrain-vict...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,NED,1987-10-01,35,0,0,...,-,-,-,-,-,-,-,-,-,-
2,3,WILCO KELDERMAN,JUMBO-VISMA,https://www.letour.fr/en/rider/3/jumbo-visma/w...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,NED,1991-03-25,32,0,0,...,-,-,-,-,-,-,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,84,ALEX KIRSCH,LIDL - TREK,https://www.letour.fr/en/rider/84/lidl-trek/al...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,LUX,1992-06-12,31,0,0,...,-,-,-,-,-,-,-,-,-,-
106,133,ALEX ARANBURU DEBA,MOVISTAR TEAM,https://www.letour.fr/en/rider/133/movistar-te...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,ESP,1995-09-19,27,0,0,...,-,-,-,-,-,-,-,-,-,-
34,43,ALBERTO BETTIOL,EF EDUCATION - EASYPOST,https://www.letour.fr/en/rider/43/ef-education...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,ITA,1993-10-29,29,0,0,...,-,-,-,-,-,-,-,-,-,-
92,115,ADRIEN PETIT,INTERMARCHÉ - CIRCUS - WANTY,https://www.letour.fr/en/rider/115/intermarche...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,FRA,1990-09-26,32,0,0,...,-,-,-,-,-,-,-,-,-,-
15,19,ADAM YATES,UAE TEAM EMIRATES,https://www.letour.fr/en/rider/19/uae-team-emi...,https://img.aso.fr/core_app/img-cycling-tdf-pn...,GBR,1992-08-07,30,1,1,...,-,-,-,-,-,-,-,-,-,-

In [27]:
riders.dtypes

bib                             int64
name                           object
team                           object
link                           object
image                          object
country                        object
birth                  datetime64[ns]
age                             int64
intermediate sprint            object
stages victory                 object
Victories                      object
Podiums                        object
1                              object
2                              object
3                              object
4                              object
5                              object
6                              object
7                              object
8                              object
9                              object
10                             object
11                             object
12                             object
13                             object
14                             object
15                             object
16                             object
17                             object
18                             object
19                             object
20                             object
21                             object
dtype: object